Repository School-of-Company/Expo-Android, pull requests merged in 2025-02, with the labels that each got.

#404 🔀 :: (#402) - 관리자 프로필 불러오기 기능 구현을 하였습니다.
  feature/user/src/main/java/com/school_of_company/user/view/UserScreen.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#408 🔀 :: (#407) - 참가자 검색 부분에 검색하기 버튼을 클릭함에 따라 검색을 구현하는 화면이 아닌, 입력이 감지됨에 따라 검색될 수 있도록 리팩터링을 하였습니다.
  core/design-system/src/main/java/com/school_of_company/design_system/component/textfield/ExpoTextField.kt
  feature/program/src/main/java/com/school_of_company/program/view/ProgramDetailParticipantManagementScreen.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor

#406 🔀 :: (#405) - UserScreen의 회원가입 요청 리스트가 화면 높이의 최대치 이상까지 많아진다면 버튼의 UI가 밀려 없어지는 문제가 있어 리스트 컴포넌트와 합쳐 해결하였습니다.
  feature/user/src/main/java/com/school_of_company/user/view/UserScreen.kt
  feature/user/src/main/java/com/school_of_company/user/view/component/SignUpRequestList.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor, 🐞 Bug

#412 🔀 :: (#411) - 박람회 자세히 보기 화면의 버튼 디자인이 변경되어 이를 수정하였습니다.
  core/design-system/src/main/java/com/school_of_company/design_system/component/button/ExpoButton.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoDetailScreen.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor

#418 🔀 :: (#417) - Ci가 성공 상태일때 리뷰하는 팀원을 맨션할 수 있도록 하였습니다.
  .github/workflows/expo_ci.yml
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#419 🔀 :: (#399) - 박람회를 생성하는 도중 다른 네비게이션으로 이동 후 다시 리컴포지션 되었을때 이미지의 데이터가 사라지는 이슈가 있어 이를 해결하였습니다.
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoCreateScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoModifyScreen.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#442 🔀 :: (#441) - 자동 로그인이 동작하는 과정에서 바로 homeRoute로 넘어가는 것이 아니라 signInRoute를 거쳐서가는 문제를 해결하였습니다.
  app/src/main/java/com/school_of_company/expo_android/MainActivity.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#436 🔀 :: (#436) 폼생성 스크린의 기능을 구현했습니다
  app/src/main/java/com/school_of_company/expo_android/navigation/ExpoNavHost.kt
  core/design-system/src/main/res/values/strings.xml
  core/model/src/main/java/com/school_of_company/model/model/form/FormRequestAndResponseModel.kt
  core/network/src/main/java/com/school_of_company/network/dto/form/all/FormRequestAndResponse.kt
  core/network/src/main/java/com/school_of_company/network/mapper/form/request/FormRequestMapper.kt
  core/network/src/main/java/com/school_of_company/network/mapper/form/response/FormResponseMapper.kt
  core/network/src/main/java/com/school_of_company/network/util/convertListToJsonMap.kt
  feature/form/src/main/java/com/school_of_company/form/navigation/FormNavigation.kt
  feature/form/src/main/java/com/school_of_company/form/view/FormCreateScreen.kt
  feature/form/src/main/java/com/school_of_company/form/view/component/FormCard.kt
  feature/form/src/main/java/com/school_of_company/form/view/component/FormCheckBoxItem.kt
  feature/form/src/main/java/com/school_of_company/form/view/component/FormDropDownItem.kt
  feature/form/src/main/java/com/school_of_company/form/view/component/FormMultiPleItem.kt
  feature/form/src/main/java/com/school_of_company/form/viewModel/.gitkeep
  feature/form/src/main/java/com/school_of_company/form/viewModel/FormCreateViewModel.kt
  feature/form/src/main/java/com/school_of_company/form/viewModel/uiState/CreateFormUiState.kt
  feature/form/src/main/java/com/school_of_company/form/viewModel/viewData/DynamicFormViewData.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, ✨ Feature

#444 🔀 :: (#443) - 뒤로가기 버튼을 빠르게 두번 클릭하면 액티비티가 종료되도록하여 사용자 입장을 개선하였습니다.
  app/src/main/java/com/school_of_company/expo_android/MainActivity.kt
Labels: 2️⃣ Priority: Medium

#446 🔀 :: (#445) - 박람회 자세히 보기 화면을 디자인 변경사항에 따라 수정하였습니다.
  app/src/main/java/com/school_of_company/expo_android/navigation/ExpoNavHost.kt
  core/design-system/src/main/java/com/school_of_company/design_system/component/button/EffectButton.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoDetailScreen.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor

#448 🔀 :: (#447) - 안드로이드 시스템바와 실제 서비스 화면이 서로 곂쳐지지않도록하여 사용자 입장을 개선하였습니다.
  app/src/main/java/com/school_of_company/expo_android/navigation/ExpoNavHost.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor

#456 🔀 :: (#455) - 로그인 화면으로 이동시 현재 남아있는 백스택이 모두 삭제될 수 있도록하여 기존에 생기던 로그아웃시 네비게이션 버그를 해결하였습니다.
  app/src/main/java/com/school_of_company/expo_android/ui/ExpoAppState.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, 🐞 Bug

#454 🔀 :: (#453) - 로그인 이후 홈 화면으로 이동할때 로그인 화면의 스택을 삭제하여 홈 화면에서 다시 로그인 화면으로 이동되는 문제를 해결하였습니다.
  app/src/main/java/com/school_of_company/expo_android/navigation/ExpoNavHost.kt
  app/src/main/java/com/school_of_company/expo_android/ui/ExpoAppState.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor
