Repository School-of-Company/Expo-Android, pull requests merged in 2025-01, with the labels that each got.

#274 🔀 :: (#270) - Standard 부분 API에서 메서드가 잘 쓰이고 있는 부분이 있어 이를 수정하였습니다.
  core/network/src/main/java/com/school_of_company/network/api/StandardAPI.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ExpoBottomSheet.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor

#276 🔀 :: (#267) - Standard 부분 QR 스캔을 하기 위한 네트워크 세팅 및 ViewModel 로직 작성을 하였습니다.
  core/data/src/main/java/com/school_of_company/data/repository/attendance/AttendanceRepository.kt
  core/data/src/main/java/com/school_of_company/data/repository/attendance/AttendanceRepositoryImpl.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/attendance/StandardQrCodeRequestUseCase.kt
  core/model/src/main/java/com/school_of_company/model/param/attendance/StandardQrCodeRequestParam.kt
  core/network/src/main/java/com/school_of_company/network/api/AttendanceAPI.kt
  core/network/src/main/java/com/school_of_company/network/datasource/attendance/AttendanceDataSource.kt
  core/network/src/main/java/com/school_of_company/network/datasource/attendance/AttendanceDataSourceImpl.kt
  core/network/src/main/java/com/school_of_company/network/dto/attendance/request/StandardQrCodeRequest.kt
  core/network/src/main/java/com/school_of_company/network/mapper/attendance/request/StandardQrCodeRequestMapper.kt
  feature/standard/build.gradle.kts
  feature/standard/src/main/java/com/school_of_company/standard/viewmodel/StandardViewModel.kt
  feature/standard/src/main/java/com/school_of_company/standard/viewmodel/uistate/StandardQrCodeUiState.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#282 🔀 :: (#268) - 바텀 네비게이션바의 디자인 변동 사항을 수용하여 수정하였습니다.
  app/src/main/java/com/school_of_company/expo_android/navigation/TopLevelDestination.kt
  app/src/main/java/com/school_of_company/expo_android/ui/ExpoApp.kt
  app/src/main/java/com/school_of_company/expo_android/ui/ExpoAppState.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor

#281 🔀 :: (#273) - 로그인 스크린의 비밀번호 텍스트필드에 비밀번호가 사용자의 클릭에 따라 확인 가능하도록 수정하였습니다.
  core/design-system/src/main/java/com/school_of_company/design_system/component/textfield/ExpoTextField.kt
  core/design-system/src/main/java/com/school_of_company/design_system/icon/ExpoIcon.kt
  core/design-system/src/main/res/drawable/ic_eye_close.xml
  core/design-system/src/main/res/drawable/ic_open_eye.xml
  feature/signin/src/main/java/com/school_of_company/navigation/SignInNavigation.kt
  feature/signin/src/main/java/com/school_of_company/view/SignInScreen.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor

#280 🔀 :: (#231) - qr read performance improve
  app/src/main/java/com/school_of_company/expo_android/navigation/ExpoNavHost.kt
  build-logic/convention/src/main/java/com/school_of_company/convention/AndroidLintConventionPlugin.kt
  core/data/src/main/java/com/school_of_company/data/repository/attendance/AttendanceRepositoryImpl.kt
  core/design-system/src/main/java/com/school_of_company/design_system/icon/ExpoIcon.kt
  core/design-system/src/main/res/drawable/qr_guide.xml
  core/design-system/src/main/res/values/strings.xml
  core/model/src/main/java/com/school_of_company/model/param/attendance/StandardQrCodeRequestParam.kt
  core/network/src/main/java/com/school_of_company/network/api/AttendanceAPI.kt
  core/network/src/main/java/com/school_of_company/network/datasource/attendance/AttendanceDataSource.kt
  core/network/src/main/java/com/school_of_company/network/dto/attendance/request/StandardQrCodeRequest.kt
  feature/program/src/main/java/com/school_of_company/program/navigation/ProgramNavigation.kt
  feature/program/src/main/java/com/school_of_company/program/util/QrReadScreenType.kt
  feature/program/src/main/java/com/school_of_company/program/util/QrcodeAnalyzer.kt
  feature/program/src/main/java/com/school_of_company/program/util/QrcodeScanner.kt
  feature/program/src/main/java/com/school_of_company/program/util/buildImageAnalysis.kt
  feature/program/src/main/java/com/school_of_company/program/util/buildPreview.kt
  feature/program/src/main/java/com/school_of_company/program/util/parseQrScanModel.kt
  feature/program/src/main/java/com/school_of_company/program/util/setupQrScanCamera.kt
  feature/program/src/main/java/com/school_of_company/program/view/QrScannerScreen.kt
  feature/program/src/main/java/com/school_of_company/program/view/component/QrScannView.kt
  feature/program/src/main/java/com/school_of_company/program/viewmodel/ProgramViewModel.kt
  feature/program/src/main/java/com/school_of_company/program/viewmodel/uistate/ReadQrCodeUiState.kt
  feature/program/src/main/java/com/school_of_company/program/viewmodel/uistate/TrainingQrCodeUiState.kt
  feature/standard/src/main/java/com/school_of_company/standard/navigation/StandardNavigation.kt
  feature/standard/src/main/java/com/school_of_company/standard/view/StandardProgramParticipantScreen.kt
  feature/training/src/main/java/com/school_of_company/training/navigation/TrainingNavigation.kt
  feature/training/src/main/java/com/school_of_company/training/view/TrainingProgramParticipantScreen.kt
Labels: 0️⃣ Priority: Critical, ⚡️performance, ✨ Feature, 🐞 Bug

#287 🔀 :: (#286) - 새로 바뀐 baseUrl이 http로 되어있어 안드로이드 스튜디오 자체에서 막는 문제를 전체 HTTP 트래픽을 허용되도록 하였습니다.
  app/src/main/AndroidManifest.xml
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#293 🔀 :: (#291) - 박람회 자세히 보기 디자인이 변경이 되어 이를 수정하였습니다.
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoDetailScreen.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, ✨ Feature

#295 🔀 :: (#294) - 백람회 생성, 수정에서의 이미지 크기 제한을 해제하였습니다.
  app/src/main/java/com/school_of_company/expo_android/navigation/ExpoNavHost.kt
  feature/expo/src/main/java/com/school_of_company/expo/navigation/ExpoNavigation.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoCreateScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoDetailScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoModifyScreen.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor

#306 🔀 :: (#299) - 회원가입 요청 기능을 구현하였습니다.
  app/src/main/java/com/school_of_company/expo_android/navigation/ExpoNavHost.kt
  core/design-system/src/main/java/com/school_of_company/design_system/theme/color/ExpoColor.kt
  core/design-system/src/main/res/values/strings.xml
  feature/user/src/main/java/com/school_of_company/user/navigation/UserNavigation.kt
  feature/user/src/main/java/com/school_of_company/user/view/UserScreen.kt
  feature/user/src/main/java/com/school_of_company/user/view/component/SignUpRequestList.kt
  feature/user/src/main/java/com/school_of_company/user/view/component/SignUpRequestListItem.kt
  feature/user/src/main/java/com/school_of_company/user/view/component/UserAllowButton.kt
  feature/user/src/main/java/com/school_of_company/user/view/component/UserDeleteButton.kt
  feature/user/src/main/java/com/school_of_company/user/viewmodel/.gitkeep
  feature/user/src/main/java/com/school_of_company/user/viewmodel/UserViewModel.kt
  feature/user/src/main/java/com/school_of_company/user/viewmodel/uistate/AllowAdminRequestUiState.kt
  feature/user/src/main/java/com/school_of_company/user/viewmodel/uistate/GetAdminRequestAllowListUiState.kt
  feature/user/src/main/java/com/school_of_company/user/viewmodel/uistate/ServiceWithdrawalUiState.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#312 🔀 :: (#311) - 각 화면의 리스트 부분에 대한 디자인 변동사항이 있어 이를 수정하였습니다.
  feature/program/src/main/java/com/school_of_company/program/view/ProgramDetailProgramScreen.kt
  feature/standard/src/main/java/com/school_of_company/standard/view/StandardProgramParticipantScreen.kt
  feature/training/src/main/java/com/school_of_company/training/view/TrainingProgramParticipantScreen.kt
  feature/user/src/main/java/com/school_of_company/user/view/UserScreen.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor

#309 🔀 :: (#302) - created expo screen communication implementation
  app/src/main/java/com/school_of_company/expo_android/ui/ExpoApp.kt
  app/src/main/java/com/school_of_company/expo_android/ui/ExpoAppState.kt
  core/design-system/src/main/res/values/strings.xml
  feature/expo/src/main/java/com/school_of_company/expo/navigation/ExpoNavigation.kt
  feature/expo/src/main/java/com/school_of_company/expo/util/formatDateToMonthDay.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoCreatedScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/CreatedExpoList.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/CreatedExpoListItem.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ExpoCreatedDeleteButton.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ExpoCreatedTable.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ExpoCreatedTopCard.kt
  feature/expo/src/main/java/com/school_of_company/expo/viewmodel/ExpoViewModel.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#317 🔀 :: (#310) - 각 UiState의 Error, Empty 상태에 보여줄 UI를 컴포넌트로 만들어 재사용할 수 있도록 하였습니다.
  core/design-system/src/main/java/com/school_of_company/design_system/component/uistate/empty/ShowEmptyState.kt
  core/design-system/src/main/java/com/school_of_company/design_system/component/uistate/error/ShowErrorState.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoCreatedScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoScreen.kt
  feature/program/src/main/java/com/school_of_company/program/view/ProgramDetailProgramScreen.kt
  feature/standard/src/main/java/com/school_of_company/standard/view/StandardProgramParticipantScreen.kt
  feature/training/src/main/java/com/school_of_company/training/view/TrainingProgramParticipantScreen.kt
  feature/user/src/main/java/com/school_of_company/user/view/UserScreen.kt
Labels: 0️⃣ Priority: Critical

#319 🔀 :: (#315) - 프로그램 화면의 디자인 변동 사항이 있어 이를 수정하였습니다.
  feature/program/src/main/java/com/school_of_company/program/view/ProgramDetailProgramScreen.kt
  feature/program/src/main/java/com/school_of_company/program/view/component/ProgramListItem.kt
  feature/program/src/main/java/com/school_of_company/program/view/component/StandardProgramListItem.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor

#320 🔀 :: (#278) - 카메라 권한 허용을 했을때 자동으로 넘어가지 않던 문제를 해결하였습니다.
  app/src/main/java/com/school_of_company/expo_android/navigation/ExpoNavHost.kt
  core/design-system/src/main/res/values/strings.xml
  feature/program/src/main/java/com/school_of_company/program/navigation/ProgramNavigation.kt
  feature/program/src/main/java/com/school_of_company/program/view/QrScannerScreen.kt
Labels: 3️⃣ Priority: Low, ♻️ Refactor

#324 🔀 :: (#323) - 프로필 디자인 변동 사항을 적용합니다.
  core/design-system/src/main/java/com/school_of_company/design_system/icon/ExpoIcon.kt
  core/design-system/src/main/res/drawable/ic_logout.xml
  feature/user/src/main/java/com/school_of_company/user/view/UserScreen.kt
  feature/user/src/main/java/com/school_of_company/user/view/component/UserBottomSheet.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor

#327 🔀 :: (#314) - add input masking when entering date
  core/design-system/src/main/java/com/school_of_company/design_system/component/textfield/ExpoTextField.kt
  core/ui/src/main/java/com/school_of_company/ui/util/autoFormatToDateTime.kt
  core/ui/src/main/java/com/school_of_company/ui/visualTransformation/DateTimeVisualTransformation.kt
  core/ui/src/test/java/com/school_of_company/ui/ExampleUnitTest.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoCreateScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoCreatedScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoModifyScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ExpoNoneLineTextField.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ExpoSettingBottomSheet.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ExpoStandardSettingBottomSheet.kt
  feature/expo/src/main/java/com/school_of_company/expo/viewmodel/ExpoViewModel.kt
Labels: 3️⃣ Priority: Low, ✨ Feature, 📝 Docs, 🪡 Want

#328 🔀 :: (#326) - 로그아웃, 회원 탈퇴 기능 구현을 하였습니다.
  app/src/main/java/com/school_of_company/expo_android/navigation/ExpoNavHost.kt
  core/design-system/src/main/res/values/strings.xml
  feature/user/src/main/java/com/school_of_company/user/navigation/UserNavigation.kt
  feature/user/src/main/java/com/school_of_company/user/view/UserScreen.kt
  feature/user/src/main/java/com/school_of_company/user/viewmodel/UserViewModel.kt
  feature/user/src/main/java/com/school_of_company/user/viewmodel/uistate/LogoutUiState.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#332 🔀 :: (#331) - 등록된 박람회에서 상태가 empty, error일때 새로고침이 되지 않는 문제가 있어 이를 수정하였습니다.
  core/design-system/src/main/res/values/strings.xml
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoCreatedScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/CreatedExpoList.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#347 🔀 :: (#346) - AuthInterceptor의 코드에서 토큰을 넣어주어야하는 경로에 토큰이 들어가지 않는 문제가 있어 이를 해결하였습니다.
  core/network/src/main/java/com/school_of_company/network/util/AuthInterceptor.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, 🐞 Bug

#355 🔀 :: (#354) - 참가자 조회 부분 모든 교원원수 참여자 부분에 디자인이 변경된 부분이 있어 이를 수정하였습니다.
  feature/program/src/main/java/com/school_of_company/program/view/component/ProgramTraineeList.kt
  feature/program/src/main/java/com/school_of_company/program/view/component/ProgramTraineeListItem.kt
  feature/program/src/main/java/com/school_of_company/program/view/component/ProgramTraineeTable.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor

#360 🔀 :: (#359) - 회원가입 요청 거절 기능 구현 및 네트워크 세팅을 하였습니다.
  core/data/src/main/java/com/school_of_company/data/repository/admin/AdminRepository.kt
  core/data/src/main/java/com/school_of_company/data/repository/admin/AdminRepositoryImpl.kt
  core/design-system/src/main/res/values/strings.xml
  core/domain/src/main/java/com/school_of_company/domain/usecase/admin/RejectAdminRequestUseCase.kt
  core/network/src/main/java/com/school_of_company/network/api/AdminAPI.kt
  core/network/src/main/java/com/school_of_company/network/datasource/admin/AdminDataSource.kt
  core/network/src/main/java/com/school_of_company/network/datasource/admin/AdminDataSourceImpl.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ExpoCreatedDeleteButton.kt
  feature/user/src/main/java/com/school_of_company/user/view/UserScreen.kt
  feature/user/src/main/java/com/school_of_company/user/view/component/SignUpRequestListItem.kt
  feature/user/src/main/java/com/school_of_company/user/view/component/UserAllowButton.kt
  feature/user/src/main/java/com/school_of_company/user/view/component/UserDeleteButton.kt
  feature/user/src/main/java/com/school_of_company/user/viewmodel/UserViewModel.kt
  feature/user/src/main/java/com/school_of_company/user/viewmodel/uistate/RejectAdminRequestUiState.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#363 🔀 :: (#362) - 참가자 조회 부분 API에 변경 사항이 생겨 수정하였습니다.
  core/data/src/main/java/com/school_of_company/data/repository/participant/ParticipantRepository.kt
  core/data/src/main/java/com/school_of_company/data/repository/participant/ParticipantRepositoryImpl.kt
  core/data/src/main/java/com/school_of_company/data/repository/trainee/TraineeRepository.kt
  core/data/src/main/java/com/school_of_company/data/repository/trainee/TraineeRepositoryImpl.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/participant/ParticipantInformationResponseUseCase.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/trainee/TraineeResponseListUseCase.kt
  core/network/src/main/java/com/school_of_company/network/api/ParticipantAPI.kt
  core/network/src/main/java/com/school_of_company/network/api/TraineeAPI.kt
  core/network/src/main/java/com/school_of_company/network/datasource/participant/ParticipantDataSource.kt
  core/network/src/main/java/com/school_of_company/network/datasource/participant/ParticipantDataSourceImpl.kt
  core/network/src/main/java/com/school_of_company/network/datasource/trainee/TraineeDataSource.kt
  core/network/src/main/java/com/school_of_company/network/datasource/trainee/TraineeDataSourceImpl.kt
  feature/program/src/main/java/com/school_of_company/program/viewmodel/ProgramViewModel.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor

#368 🔀 :: (#364) - 참가자 명단 검색 기능을 구현하였습니다.
  core/design-system/src/main/java/com/school_of_company/design_system/icon/ExpoIcon.kt
  core/design-system/src/main/res/drawable/ic_search.xml
  feature/program/src/main/java/com/school_of_company/program/view/ProgramDetailParticipantManagementScreen.kt
  feature/program/src/main/java/com/school_of_company/program/viewmodel/ProgramViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#377 🔀 :: (#376) - 박람회 수정, 생성 API가 변동되어 이를 수정합니다.
  core/data/src/main/java/com/school_of_company/data/repository/expo/ExpoRepository.kt
  core/data/src/main/java/com/school_of_company/data/repository/expo/ExpoRepositoryImpl.kt
  core/data/src/main/java/com/school_of_company/data/repository/standard/StandardRepository.kt
  core/data/src/main/java/com/school_of_company/data/repository/standard/StandardRepositoryImpl.kt
  core/data/src/main/java/com/school_of_company/data/repository/training/TrainingRepository.kt
  core/data/src/main/java/com/school_of_company/data/repository/training/TrainingRepositoryImpl.kt
  core/design-system/src/main/java/com/school_of_company/design_system/component/bottomsheet/ExpoSettingDialog.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/expo/ModifyExpoInformationUseCase.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/expo/RegisterExpoInformationUseCase.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/standard/ModifyStandardProgramUseCase.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/standard/RegisterStandardListProgramUseCase.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/standard/RegisterStandardProgramUseCase.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/training/ModifyTrainingProgramUseCase.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/training/RegisterTrainingProgramListUseCase.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/training/RegisterTrainingProgramUseCase.kt
  core/model/src/main/java/com/school_of_company/model/model/standard/StandardRequestModel.kt
  core/model/src/main/java/com/school_of_company/model/model/training/TrainingDtoModel.kt
  core/model/src/main/java/com/school_of_company/model/param/expo/ExpoCreateRequestParam.kt
  core/model/src/main/java/com/school_of_company/model/param/expo/ExpoModifyRequestParam.kt
  core/network/src/main/java/com/school_of_company/network/api/ExpoAPI.kt
  core/network/src/main/java/com/school_of_company/network/api/StandardAPI.kt
  core/network/src/main/java/com/school_of_company/network/api/TrainingAPI.kt
  core/network/src/main/java/com/school_of_company/network/datasource/expo/ExpoDataSource.kt
  core/network/src/main/java/com/school_of_company/network/datasource/expo/ExpoDataSourceImpl.kt
  core/network/src/main/java/com/school_of_company/network/datasource/standard/StandardDataSource.kt
  core/network/src/main/java/com/school_of_company/network/datasource/standard/StandardDataSourceImpl.kt
  core/network/src/main/java/com/school_of_company/network/datasource/training/TrainingDataSource.kt
  core/network/src/main/java/com/school_of_company/network/datasource/training/TrainingDataSourceImpl.kt
  core/network/src/main/java/com/school_of_company/network/dto/expo/request/ExpoCreateRequest.kt
  core/network/src/main/java/com/school_of_company/network/dto/expo/request/ExpoModifyRequest.kt
  core/network/src/main/java/com/school_of_company/network/dto/expo/response/ExpoResponse.kt
  core/network/src/main/java/com/school_of_company/network/dto/standard/request/.gitkeep
  core/network/src/main/java/com/school_of_company/network/dto/standard/request/StandardRequest.kt
  core/network/src/main/java/com/school_of_company/network/dto/training/all/TrainingDto.kt
  core/network/src/main/java/com/school_of_company/network/dto/training/request/.gitkeep
  core/network/src/main/java/com/school_of_company/network/mapper/expo/request/ExpoCreateRequestMapper.kt
  core/network/src/main/java/com/school_of_company/network/mapper/expo/request/ExpoModifyRequestMapper.kt
  core/network/src/main/java/com/school_of_company/network/mapper/expo/request/ExpoRequestMapper.kt
  core/network/src/main/java/com/school_of_company/network/mapper/expo/response/ExpoResponseMapper.kt
  core/network/src/main/java/com/school_of_company/network/mapper/standard/request/.gitkeep
  core/network/src/main/java/com/school_of_company/network/mapper/standard/request/StandardRequestMapper.kt
  core/network/src/main/java/com/school_of_company/network/mapper/training/request/.gitkeep
  core/network/src/main/java/com/school_of_company/network/mapper/training/request/TrainingDtoRequestMapper.kt
  core/network/src/main/java/com/school_of_company/network/mapper/training/response/TrainingDtoResponseMapper.kt
  core/ui/src/main/java/com/school_of_company/ui/util/FormatServerDate.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoCreateScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoModifyScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ExpoAddTextField.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ExpoSettingBottomSheet.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ExpoStandardAddTextField.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ExpoStandardSettingBottomSheet.kt
  feature/expo/src/main/java/com/school_of_company/expo/viewmodel/ExpoViewModel.kt
  feature/signin/src/main/java/com/school_of_company/viewmodel/SignInViewModel.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor

#382 🔀 :: (#368) - api latitude longitude update
  core/model/src/main/java/com/school_of_company/model/model/expo/ExpoRequestAndResponseModel.kt
  core/model/src/main/java/com/school_of_company/model/param/expo/ExpoCreateRequestParam.kt
  core/model/src/main/java/com/school_of_company/model/param/expo/ExpoModifyRequestParam.kt
  core/network/src/main/java/com/school_of_company/network/dto/expo/request/ExpoCreateRequest.kt
  core/network/src/main/java/com/school_of_company/network/dto/expo/request/ExpoModifyRequest.kt
  core/network/src/main/java/com/school_of_company/network/dto/expo/response/ExpoResponse.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoCreateScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoModifyScreen.kt
Labels: ♻️ Refactor

#384 🔀 :: (#369) - Authenticator의 코드에 리팩터링이 필요한 부분이 있어 리팩터링을 진행하였습니다.
  core/network/src/main/java/com/school_of_company/network/util/AuthInterceptor.kt
  core/network/src/main/java/com/school_of_company/network/util/TokenAuthenticator.kt
Labels: 3️⃣ Priority: Low, ♻️ Refactor

#385 🔀 :: (#381) - 등록된 박람회 부분에서 리스트가 fillMaxHeight의 상태가 되면 버튼의 Ui가 뭉개져 사라지는 문제를 해결하였습니다.
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoCreatedScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/CreatedExpoList.kt
  feature/expo/src/main/java/com/school_of_company/expo/viewmodel/ExpoViewModel.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor, 🐞 Bug

#388 🔀 :: (#387) - 폼 파트 네트워크 세팅을 하였습니다.
  app/build.gradle.kts
  core/data/src/main/java/com/school_of_company/data/di/RepositoryModule.kt
  core/data/src/main/java/com/school_of_company/data/repository/form/FormRepository.kt
  core/data/src/main/java/com/school_of_company/data/repository/form/FormRepositoryImpl.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/form/CreateFormUseCase.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/form/DeleteFormUseCase.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/form/GetFormUseCase.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/form/ModifyFormUseCase.kt
  core/network/src/main/java/com/school_of_company/network/api/FormAPI.kt
  core/network/src/main/java/com/school_of_company/network/dto/form/.gitkeep
  feature/form/.gitignore
  feature/form/build.gradle.kts
  feature/form/consumer-rules.pro
  feature/form/proguard-rules.pro
  feature/form/src/androidTest/java/com/school_of_company/form/ExampleInstrumentedTest.kt
  feature/form/src/main/AndroidManifest.xml
  feature/form/src/main/java/com/school_of_company/form/enum/FromType.kt
  feature/form/src/main/java/com/school_of_company/form/enum/ParticipantType.kt
  feature/form/src/main/java/com/school_of_company/form/navigation/.gitkeep
  feature/form/src/main/java/com/school_of_company/form/view/.gitkeep
  feature/form/src/main/java/com/school_of_company/form/viewModel/.gitkeep
  feature/form/src/test/java/com/school_of_company/form/ExampleUnitTest.kt
  settings.gradle.kts
Labels: 1️⃣ Priority: High, ⚙ Setting

#396 🔀 :: (#395) - Moshi Codegen 기반의 객체 생성 부분에서 불필요한 옵션이 존재해 이를 삭제하였습니다.
  core/network/src/main/java/com/school_of_company/network/di/NetworkModule.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor

#398 🔀 :: (#397) - 박람회 프로필 정보를 불러오는 기능을 구현하기 위해 네트워크 세팅을 하였습니다.
  core/data/src/main/java/com/school_of_company/data/repository/admin/AdminRepository.kt
  core/data/src/main/java/com/school_of_company/data/repository/admin/AdminRepositoryImpl.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/admin/GetAdminInformationUseCase.kt
  core/model/src/main/java/com/school_of_company/model/entity/admin/AdminInformationResponseEntity.kt
  core/network/src/main/java/com/school_of_company/network/api/AdminAPI.kt
  core/network/src/main/java/com/school_of_company/network/datasource/admin/AdminDataSource.kt
  core/network/src/main/java/com/school_of_company/network/datasource/admin/AdminDataSourceImpl.kt
  core/network/src/main/java/com/school_of_company/network/dto/admin/response/AdminInformationResponse.kt
  core/network/src/main/java/com/school_of_company/network/mapper/admin/response/AdminInformationResponseMapper.kt
  feature/user/src/main/java/com/school_of_company/user/viewmodel/UserViewModel.kt
  feature/user/src/main/java/com/school_of_company/user/viewmodel/uistate/GetAdminInformationUiState.kt
Labels: 1️⃣ Priority: High, ⚙ Setting
