Repository School-of-Company/Expo-Android, pull requests merged in 2025-04, with the labels that each got.

#503 🔀 :: (#502) - 불필요한 Authorization 삭제
  core/network/src/main/java/com/school_of_company/network/util/AuthInterceptor.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor

#512 🔀 :: (#504) - 박람회 통계보기 화면을 퍼블리싱 하였습니다.
  app/src/main/java/com/school_of_company/expo_android/navigation/ExpoNavHost.kt
  feature/expo/src/main/java/com/school_of_company/expo/navigation/ExpoNavigation.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoChartScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoDetailScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/DetailsPieChart.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/DetailsPieChartItem.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ExpoChartButton.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ParticipantPieChart.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#515 🔀 :: (#513) - expoChartScreen의 막대그래프를 퍼블리싱했습니다
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoChartScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ParticipantBarGraph.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ParticipantPieChart.kt
Labels: 1️⃣ Priority: High, ⚡️ Simple, ✨ Feature

#517 🔀 :: (#516) - 통계 화면이 불필요해져 관련된 컴포넌트를 삭제하였습니다.
  app/src/main/java/com/school_of_company/expo_android/navigation/ExpoNavHost.kt
  feature/expo/src/main/java/com/school_of_company/expo/navigation/ExpoNavigation.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoChartScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoDetailScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/DetailsPieChart.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/DetailsPieChartItem.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ParticipantBarGraph.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ParticipantPieChart.kt
Labels: 1️⃣ Priority: High

#518 🔀 :: (#514) - AppConfigModule의 package path에 올바른 경로가 들어가도록 수정하였습니다.
  app/src/main/java/com/school_of_company/expo_android/di/AppConfigModule.kt
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#523 🔀 :: (#522) - expo의 주소 관련 기능들이 정상 작동 하도록 수정했습니다
  core/data/src/main/java/com/school_of_company/data/repository/kakao/KakaoRepositoryImpl.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoAddressSearchScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoCreateScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoModifyScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/viewmodel/ExpoViewModel.kt
  feature/form/src/main/java/com/school_of_company/form/view/component/FormToggleButton.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#530 🔀 :: (#529) - 박람회 동적폼, 만족도 조사 생성 여부 네트워크 세팅을 하였습니다.
  core/data/src/main/java/com/school_of_company/data/repository/expo/ExpoRepository.kt
  core/data/src/main/java/com/school_of_company/data/repository/expo/ExpoRepositoryImpl.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/expo/CheckExpoSurveyDynamicFormEnableUseCase.kt
  core/model/src/main/java/com/school_of_company/model/entity/expo/ExpoSurveyDynamicFormEnabledEntity.kt
  core/network/src/main/java/com/school_of_company/network/api/ExpoAPI.kt
  core/network/src/main/java/com/school_of_company/network/datasource/expo/ExpoDataSource.kt
  core/network/src/main/java/com/school_of_company/network/datasource/expo/ExpoDataSourceImpl.kt
  core/network/src/main/java/com/school_of_company/network/dto/expo/response/ExpoSurveyDynamicFormEnabledResponse.kt
  core/network/src/main/java/com/school_of_company/network/mapper/expo/response/ExpoSurveyDynamicFormEnabledResponseMapper.kt
  feature/expo/src/main/java/com/school_of_company/expo/viewmodel/uistate/CheckExpoSurveyDynamicFormEnableUiState.kt
Labels: 1️⃣ Priority: High

#533 🔀 :: (#532) - 폼 생성 및 수정 화면에 디자인과 다른 부분이 있어 수정하였습니다.
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoDetailScreen.kt
  feature/form/src/main/java/com/school_of_company/form/view/FormCreateScreen.kt
  feature/form/src/main/java/com/school_of_company/form/view/FormModifyScreen.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor

#537 🔀 :: (#536) - 폼 모듈을 리팩터링하였습니다.
  core/design-system/src/main/java/com/school_of_company/design_system/component/textfield/ExpoTextField.kt
  feature/form/src/main/java/com/school_of_company/form/view/FormModifyScreen.kt
  feature/form/src/main/java/com/school_of_company/form/view/component/FormCheckBoxItem.kt
  feature/form/src/main/java/com/school_of_company/form/view/component/FormImageItem.kt
  feature/form/src/main/java/com/school_of_company/form/view/component/PersonaInformationFormCard.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor

#541 🔀 :: (#540) - 폼 생성 이후 홈화면으로 이동하는 화면을 퍼블리싱하였습니다.
  app/src/main/java/com/school_of_company/expo_android/navigation/ExpoNavHost.kt
  core/design-system/build.gradle.kts
  core/design-system/src/main/java/com/school_of_company/design_system/component/lottie/CheckLottie.kt
  core/design-system/src/main/res/raw/lottie.json
  feature/expo/src/main/java/com/school_of_company/expo/navigation/ExpoNavigation.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoNavigationHomeScreen.kt
  feature/form/src/main/java/com/school_of_company/form/navigation/FormNavigation.kt
  feature/form/src/main/java/com/school_of_company/form/view/FormCreateScreen.kt
Labels: 1️⃣ Priority: High

#549 🔀 :: (#548) - 프로그램 QR 스캔이 되지 않고 앱이 터지는 문제가 있었습니다.
  core/network/src/main/java/com/school_of_company/network/api/AttendanceAPI.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#551 🔀 :: (#550) - 일반, 연수 프로그램별 출석 리스트가 명세서에 나온 스팩과 달라 통신이 되지 않는 문제를 해결하였습니다.
  core/model/src/main/java/com/school_of_company/model/entity/standard/StandardAttendListResponseEntity.kt
  core/model/src/main/java/com/school_of_company/model/entity/training/TeacherTrainingProgramResponseEntity.kt
  core/network/src/main/java/com/school_of_company/network/dto/standard/response/StandardAttendListResponse.kt
  core/network/src/main/java/com/school_of_company/network/dto/training/response/TeacherTrainingProgramResponse.kt
  core/network/src/main/java/com/school_of_company/network/mapper/standard/response/StandardAttendListResponseMapper.kt
  core/network/src/main/java/com/school_of_company/network/mapper/training/response/TeacherTrainingProgramResponseMapper.kt
  feature/standard/src/main/java/com/school_of_company/standard/view/StandardProgramParticipantScreen.kt
  feature/standard/src/main/java/com/school_of_company/standard/view/component/StandardParticipantList.kt
  feature/standard/src/main/java/com/school_of_company/standard/view/component/StandardProgramParticipantListItem.kt
  feature/training/src/main/java/com/school_of_company/training/view/TrainingProgramParticipantScreen.kt
  feature/training/src/main/java/com/school_of_company/training/view/component/TrainingProgramParticipantList.kt
  feature/training/src/main/java/com/school_of_company/training/view/component/TrainingProgramParticipantListItem.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor

#553 🔀 :: (#552) - 메인 스크린에서 사용되는 필터 버튼 디자인과 모달이 추가되어 퍼블리싱하였습니다.
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ExpoFilterButton.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ExpoFormFilterDialog.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ExpoFormFilterGroupButton.kt
Labels: 1️⃣ Priority: High

#555 🔀 :: (#554) - 박람회 동적폼, 만족도 조사 생성 여부 필터 기능을 구현하였습니다.
  core/model/src/main/java/com/school_of_company/model/entity/expo/ExpoSurveyDynamicFormEnabledEntity.kt
  core/network/src/main/java/com/school_of_company/network/dto/expo/response/ExpoSurveyDynamicFormEnabledResponse.kt
  feature/expo/src/main/java/com/school_of_company/expo/enum/FilterOptionEnum.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ExpoDetailModifyDialog.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ExpoFormFilterDialog.kt
  feature/expo/src/main/java/com/school_of_company/expo/viewmodel/ExpoViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#558 🔀 :: (#557) - 필터 상태 불일치 문제를 해결하였습니다.
  feature/expo/src/main/java/com/school_of_company/expo/viewmodel/ExpoViewModel.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#560 🔀 :: (#559) - 박람회 동적폼, 만족도 조사 생성 여부 API에서 사용하지 않는 필드를 삭제하였습니다.
  core/model/src/main/java/com/school_of_company/model/entity/expo/ExpoSurveyDynamicFormEnabledEntity.kt
  core/network/src/main/java/com/school_of_company/network/dto/expo/response/ExpoSurveyDynamicFormEnabledResponse.kt
  core/network/src/main/java/com/school_of_company/network/mapper/expo/response/ExpoSurveyDynamicFormEnabledResponseMapper.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#563 🔀 :: (#562) - 불필요한 앱 화면 회전을 막았습니다.
  app/src/main/AndroidManifest.xml
Labels: 1️⃣ Priority: High

#573 🔀 :: (#568) - 전체 HTTP 트래픽을 허용하도록 되어있어 이를 막고 HTTPS만 허용되도록 수정하였습니다.
  app/src/main/AndroidManifest.xml
Labels: 0️⃣ Priority: Critical, ♻️ Refactor

#587 🔀 :: (586) - 현재 앱이 30의 API 수준을 타겟팅하고 있지만, 보안 및 성능에 최적화된 최신 API를 기반으로 앱을 빌드하려면 API 수준 34 이상을 타겟팅하도록 수정하였습니다.
  build-logic/convention/src/main/java/com/school_of_company/convention/AndroidApplicationConventionPlugin.kt
Labels: 0️⃣ Priority: Critical, 🌏 Deploy

#592 🔀 :: (#590) - 배포 환경에서 생기는 오류를 해결하였습니다.
  app/src/main/AndroidManifest.xml
  build-logic/convention/src/main/java/com/school_of_company/convention/AndroidApplicationConventionPlugin.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoDetailScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoModifyScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ExpoFormFilterDialog.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ExpoFormFilterGroupButton.kt
Labels: 0️⃣ Priority: Critical, 🌏 Deploy, 🐞 Bug

#603 🔀 :: (#595) - 휴대전화 인증 성공 이후에는 버튼 Disable 처리하였습니다.
  feature/signup/src/main/java/com/school_of_company/signup/view/SignUpScreen.kt
Labels: 0️⃣ Priority: Critical

#602 🔀 :: (#596) - 앱 이름이 Expo가 아닌 Expo-Android로 되어있어 수정하였습니다.
  app/src/main/res/values/strings.xml
Labels: 0️⃣ Priority: Critical

#601 🔀 :: (#597) - 회원가입 로직에서 companion object에 상수 NAME과 NICKNAME이 같은 값을 향하고 있는 문제를 해결하였습니다.
  feature/signup/src/main/java/com/school_of_company/signup/viewmodel/SignUpViewModel.kt
Labels: 0️⃣ Priority: Critical

#600 🔀 :: (#598) - 회원가입 요청 리스트 아이템이 fillMaxWidth의 크기를 넘어갔을때 bottom padding 적용이 되어있지 않은 문제를 해결하였습니다.
  feature/user/src/main/java/com/school_of_company/user/view/component/SignUpRequestList.kt
Labels: 0️⃣ Priority: Critical

#607 🔀 :: (#606) - 박람회 자세히 -> 문자보내기 버튼 Disable 처리하였습니다.
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoDetailScreen.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor

#610 🔀 :: (#609) - 박람회 생성시 필수 항목에 *표시를 하였습니다.
  core/design-system/src/main/java/com/school_of_company/design_system/component/textfield/ExpoTextField.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoCreateScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoModifyScreen.kt
  feature/sms/src/main/java/com/school_of_company/sms/view/SendMessageScreen.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#612 🔀 :: (#611) - 박람회 상세 데이터들이 수정 및 생성할때 데이터가 초기화되지 않는 문제를 해결하였습니다.
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoModifyScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/viewmodel/ExpoViewModel.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, 🐞 Bug

#616 🔀 :: (#615) - 박람회 수정하기 시작일과 마감일 텍스트필드의 정렬이 맞지않아 수정하였습니다.
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoModifyScreen.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor

#619 🔀 :: (#618) - 엑스포 수정시에 이미지를 무조건 제업로드 해야하는 문제를 해결했습니다
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoModifyScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/viewmodel/ExpoViewModel.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, 🐞 Bug

#621 🔀 :: (#620) - 박람회 폼 생성, 수정 파트 에러 핸들링을 자세히 하였습니다.
  core/design-system/src/main/res/values/strings.xml
  feature/form/build.gradle.kts
  feature/form/src/main/java/com/school_of_company/form/view/FormCreateScreen.kt
  feature/form/src/main/java/com/school_of_company/form/view/FormModifyScreen.kt
  feature/form/src/main/java/com/school_of_company/form/viewModel/FormViewModel.kt
  feature/form/src/main/java/com/school_of_company/form/viewModel/uiState/FormUiState.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor
