Repository School-of-Company/Expo-Android, pull requests merged in 2025-03, with the labels that each got.

#493 🔀 :: (#486) - 박람회 자세히 보기 화면에서 소개글 부분에 Read More(Less) 기능을 구현을 추가하였습니다.
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoDetailScreen.kt
Labels: 2️⃣ Priority: Medium

#495 🔀 :: (#494) - 디자인과 구현한 코드와 차이점이 있어 수정을 하였습니다.
  .github/workflows/expo_ci.yml
  core/design-system/src/main/java/com/school_of_company/design_system/component/textfield/ExpoTextField.kt
  core/ui/src/main/java/com/school_of_company/ui/preview/ExpoPreviews.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoAddressSearchScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoCreateScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoCreatedScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoDetailScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/CreatedExpoListItem.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ExpoCreatedTable.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ExpoKakaoMapComponent.kt
  feature/sms/src/main/java/com/school_of_company/sms/view/SendMessageScreen.kt
  feature/sms/src/main/java/com/school_of_company/sms/view/component/SendMessageTopBar.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor

#500 🔀 :: (#499) - formToggleButton 의 드래그가 끝나면 무조건 드래그 시작점의 반대로 이동하는 버그를 수정했습니다
  feature/form/src/main/java/com/school_of_company/form/view/component/FormToggleButton.kt
Labels: 2️⃣ Priority: Medium

#502 🔀 :: (#501) - 박람회 사전 및 현장 신청 관람객 정보 API에 변동 사항이 존재하여 이를 수정하였습니다.
  core/data/src/main/java/com/school_of_company/data/repository/participant/ParticipantRepository.kt
  core/data/src/main/java/com/school_of_company/data/repository/participant/ParticipantRepositoryImpl.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/participant/ParticipantInformationResponseUseCase.kt
  core/model/src/main/java/com/school_of_company/model/entity/participant/ParticipantInformationResponseEntity.kt
  core/network/src/main/java/com/school_of_company/network/api/ParticipantAPI.kt
  core/network/src/main/java/com/school_of_company/network/datasource/participant/ParticipantDataSource.kt
  core/network/src/main/java/com/school_of_company/network/datasource/participant/ParticipantDataSourceImpl.kt
  core/network/src/main/java/com/school_of_company/network/dto/participant/response/ParticipantInformationResponse.kt
  core/network/src/main/java/com/school_of_company/network/mapper/participant/response/ParticipantInformationResponseMapper.kt
  feature/program/src/main/java/com/school_of_company/program/view/ProgramDetailParticipantManagementScreen.kt
  feature/program/src/main/java/com/school_of_company/program/view/component/ProgramDetailParticipantManagementList.kt
  feature/program/src/main/java/com/school_of_company/program/view/component/ProgramDetailParticipantManagementListItem.kt
  feature/program/src/main/java/com/school_of_company/program/view/component/ProgramTraineeList.kt
  feature/program/src/main/java/com/school_of_company/program/viewmodel/ProgramViewModel.kt
  feature/program/src/main/java/com/school_of_company/program/viewmodel/uistate/ParticipantResponseListUiState.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor

#507 🔀 :: (#506) - 박람회 자세히 보기 화면에 디자인 변동사항이 존재하여 이를 수정합니다.
  core/ui/src/main/java/com/school_of_company/ui/util/FormatServerDate.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoDetailScreen.kt
Labels: 1️⃣ Priority: High

#508 🔀 :: (#505) - 로딩중일때 LoadingDot가 띄워지도록 하였습니다.(로딩 애니메이션 추가)
  core/design-system/src/main/java/com/school_of_company/design_system/component/loading/LoadingDot.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoCreateScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoDetailScreen.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature
