Repository School-of-Company/Expo-Android, pull requests merged in 2025-05, with the labels that each got.

#625 🔀 :: (#623) - Admin 도메인에서 빈약한 도메인 모델 제거 및 Repository 기반 구조로 리팩터링하였습니다.
  build-logic/convention/src/main/java/com/school_of_company/convention/AndroidFeatureConventionPlugin.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/admin/AllowAdminRequestUseCase.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/admin/GetAdminInformationUseCase.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/admin/GetAdminRequestAllowListUseCase.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/admin/RejectAdminRequestUseCase.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/admin/ServiceWithdrawalUseCase.kt
  feature/user/src/main/java/com/school_of_company/user/viewmodel/UserViewModel.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#635 Revert "🔀 :: (#624) - juso 도메인의 useCase를 삭제 했습니다"
  core/data/src/main/java/com/school_of_company/data/repository/juso/AddressRepository.kt
  core/data/src/main/java/com/school_of_company/data/repository/juso/AddressRepositoryImpl.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/juso/GetAddressUseCase.kt
  feature/expo/src/main/java/com/school_of_company/expo/viewmodel/ExpoViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#632 🔀 :: (#631) - kakao의 useCase를 삭제했습니다
  core/data/src/main/java/com/school_of_company/data/repository/kakao/KakaoRepository.kt
  core/data/src/main/java/com/school_of_company/data/repository/kakao/KakaoRepositoryImpl.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/kakao/GetCoordinatesToAddressUseCase.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/kakao/GetCoordinatesUseCase.kt
  feature/expo/src/main/java/com/school_of_company/expo/viewmodel/ExpoViewModel.kt
Labels: 3️⃣ Priority: Low, ♻️ Refactor

#643 🔀 :: (#641) - 박람회 삭제 성공 이후 바로 리스트 상태 업데이트를 할 수 있도록 하였습니다.
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoCreatedScreen.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor

#658 🔀 :: (#655) - training 관련 useCase 를 삭제했습니다
  core/domain/src/main/java/com/school_of_company/domain/usecase/training/DeleteTrainingProgramUseCase.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/training/TeacherTrainingProgramListUseCase.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/training/TrainingProgramListUseCase.kt
  feature/expo/src/main/java/com/school_of_company/expo/viewmodel/ExpoViewModel.kt
  feature/program/src/main/java/com/school_of_company/program/viewmodel/ProgramViewModel.kt
  feature/training/src/main/java/com/school_of_company/training/viewmodel/TrainingViewModel.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#656 🔀 :: (#653) - form 관련 useCase 를 삭제했습니다
  core/domain/src/main/java/com/school_of_company/domain/usecase/form/CreateFormUseCase.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/form/DeleteFormUseCase.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/form/GetFormUseCase.kt
  core/domain/src/main/java/com/school_of_company/domain/usecase/form/ModifyFormUseCase.kt
  feature/form/build.gradle.kts
  feature/form/src/main/java/com/school_of_company/form/viewModel/FormViewModel.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#657 🔀 :: (#654) - trainee 관련 useCase 를 삭제했습니다
  core/domain/src/main/java/com/school_of_company/domain/usecase/trainee/TraineeResponseListUseCase.kt
  feature/program/src/main/java/com/school_of_company/program/viewmodel/ProgramViewModel.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#662 🔀 :: (#661) - 도메인 모듈이 남아있어 삭제하였습니다.
  app/build.gradle.kts
  build-logic/convention/src/main/java/com/school_of_company/convention/AndroidFeatureConventionPlugin.kt
  core/domain/.gitignore
  core/domain/build.gradle.kts
  core/domain/consumer-rules.pro
  core/domain/proguard-rules.pro
  core/domain/src/androidTest/java/com/school_of_company/domain/ExampleInstrumentedTest.kt
  core/domain/src/main/AndroidManifest.xml
  core/domain/src/test/java/com/school_of_company/domain/ExampleUnitTest.kt
  settings.gradle.kts
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#638 🔀 :: (#637) - 유효하지 않은 이미지가 업로드되는것처럼 보이는 문제를 해결했습니다
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoCreateScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoModifyScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/viewmodel/ExpoViewModel.kt
Labels: 0️⃣ Priority: Critical

#673 🔀 :: (#671) - User 모듈 recomposition 최적화를 하였습니다.
  core/model/build.gradle.kts
  core/model/src/main/java/com/school_of_company/model/entity/admin/AdminRequestAllowListResponseEntity.kt
  gradle/libs.versions.toml
Labels: 2️⃣ Priority: Medium, ♻️ Refactor, ⚡️performance

#677 🔀 :: (#676) - Standard 모듈 Recomposition 최적화를 진행하였습니다.
  core/model/src/main/java/com/school_of_company/model/entity/standard/StandardAttendListResponseEntity.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor, ⚡️performance

#678 🔀 :: (#675) - App 모듈 Recomposition 성능 최적화를 진행하였습니다.
  app/build.gradle.kts
  app/src/main/java/com/school_of_company/expo_android/navigation/TopLevelDestination.kt
  app/src/main/java/com/school_of_company/expo_android/ui/ExpoApp.kt
  app/src/main/java/com/school_of_company/expo_android/ui/ExpoAppState.kt
  gradle/libs.versions.toml
Labels: 2️⃣ Priority: Medium, ♻️ Refactor, ⚡️performance

#682 🔀 ::(#680) - Training 모듈 Recomposition 성능 최적화를 진행하였습니다.
  core/model/src/main/java/com/school_of_company/model/entity/training/TeacherTrainingProgramResponseEntity.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor, ⚡️performance

#689 🔀 :: (#688) - Expo 모듈 Recomposition 최적화를 진행하였습니다.
  core/model/src/main/java/com/school_of_company/model/entity/expo/ExpoListResponseEntity.kt
  core/model/src/main/java/com/school_of_company/model/model/juso/JusoModel.kt
  core/model/src/main/java/com/school_of_company/model/param/expo/ExpoCreateRequestParam.kt
  core/model/src/main/java/com/school_of_company/model/param/expo/ExpoModifyRequestParam.kt
  feature/expo/src/main/java/com/school_of_company/expo/enum/FilterOptionEnum.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoAddressSearchScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoCreateScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoModifyScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/ExpoScreen.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ExpoAddTextField.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ExpoFormFilterDialog.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ExpoFormFilterGroupButton.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ExpoSettingBottomSheet.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ExpoStandardAddTextField.kt
  feature/expo/src/main/java/com/school_of_company/expo/view/component/ExpoStandardSettingBottomSheet.kt
  feature/expo/src/main/java/com/school_of_company/expo/viewmodel/ExpoViewModel.kt
  feature/expo/src/main/java/com/school_of_company/expo/viewmodel/uistate/GetAddressUiState.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor, ⚡️performance

#697 🔀 :: (#696) - SignUpRequestList에 key 값을 이용한 최적화 적용
  feature/user/src/main/java/com/school_of_company/user/view/component/SignUpRequestList.kt
Labels: 3️⃣ Priority: Low, ♻️ Refactor, ⚡️performance
